package com.mexcorgo.component;

public enum DataReference {
    LEAD_PROSECUTOR,
    CORPORATE_REFERENCE,
    BULK_DIRECTLY,
    LEAD_REFERENCE_PROSECUTOR,
    BULK_TRANSFER_LIST,
    GMB,
    LEAD_PURCHASE,
    CAMPAIGNING,
    SOCIAL_MEDIA_MARKETING,
    ASSOCIATE_PARTNER,
    SALES_TEAM_REFERRAL,
    OTHER
}
