package com.mexcorgo.component;

public enum QuatationStatus {
    QUOTATION_CREATED,
    SENT_TO_SERVICE_PROVIDERS,
    SERVICE_PROVIDER_RESPONSE_RECEIVED,
    PURCHASE_REVIEW_COMPLETED,
    SENT_TO_PRICING_EXECUTIVE,
    PRICING_FINALIZED_AND_SENT_TO_SALES,
    SENT_TO_CUSTOMER,
    CUSTOMER_APPROVED,
    CUSTOMER_REJECTED
}
