package com.mexcorgo.component;

public enum WayOfLead {
    VENDOR,
    REFERENCE,
    BULK_LIST,
    PERSONAL_CLIENT,
    GMB,
    LEAD_PURCHASE,
    SOCIAL_MEDIA,
    MARKETING,
    PHYSICAL_LINK,
    ADVERTISEMENT,
    ASSOCIATED_PARTNER,
    MOVING_PARTNER,
    SALES_TEAM_REFERRAL,
    OTHER
}
